name       : lmms
version    : 1.2.1
release    : 13
source     :
    - git|https://github.com/LMMS/lmms.git : v1.2.1
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : LMMS is a free cross-platform alternative to commercial programs like FL Studio®
description: |
    LMMS is a free cross-platform alternative to commercial programs like FL Studio®, which allow you to produce music with your computer. This includes the creation of melodies and beats, the synthesis and mixing of sounds, and arranging of samples. You can have fun with your MIDI-keyboard and much more; all in a user-friendly and modern interface.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(fluidsynth)
    - pkgconfig(fontconfig)
    - pkgconfig(gig)
    - pkgconfig(jack)
    - pkgconfig(libpulse)
    - pkgconfig(ogg)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(samplerate)
    - pkgconfig(sdl)
    - pkgconfig(sndfile)
    - pkgconfig(vorbis)
    - pkgconfig(xcb-util)
    - pkgconfig(xft)
    - carla-devel
    - fltk-devel
    - ladspa-devel
    - lame-devel
    - qt5-tools-devel
    - sndio-devel
    - stk-devel
    - xcb-util-keysyms-devel
setup      : |
    %cmake_ninja -DCMAKE_INSTALL_PREFIX=/usr \
                 -DCMAKE_INSTALL_LIBDIR=lib \
                 -DWANT_VST_NOWINE=ON \
                 -DWANT_SOUNDIO=OFF \
                 -DWANT_QT5=ON .
build      : |
    %ninja_build
install    : |
    %ninja_install
    rm $installdir/usr/lib/*.a
