name       : lmms
version    : 1.2.0
release    : 10
source     :
    - git|https://github.com/LMMS/lmms.git : v1.2.0
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : LMMS is a free cross-platform alternative to commercial programs like FL Studio®
description: |
    LMMS is a free cross-platform alternative to commercial programs like FL Studio®, which allow you to produce music with your computer. This includes the creation of melodies and beats, the synthesis and mixing of sounds, and arranging of samples. You can have fun with your MIDI-keyboard and much more; all in a user-friendly and modern interface.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(fluidsynth)
    - pkgconfig(fontconfig)
    - pkgconfig(jack)
    - pkgconfig(libpulse)
    - pkgconfig(ogg)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(Qt5Core)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(samplerate)
    - pkgconfig(sdl)
    - pkgconfig(sndfile)
    - pkgconfig(vorbis)
    - pkgconfig(xcb-util)
    - pkgconfig(xft)
    - carla-devel
    - fltk-devel
    - ladspa-devel
    - lame-devel
    - libgcc-32bit
    - libpth-32bit-devel
    - qt5-tools-devel
    - sndio-devel
    - stk-devel
    - wine-32bit-devel
    - xcb-util-keysyms-devel
setup      : |
    # Build with libgig supprot diabled until we can get lmms to load it from /usr/lib/libgig/ instead of /usr/lib/.
    %cmake_ninja -DCMAKE_INSTALL_PREFIX=/usr \
                 -DCMAKE_INSTALL_LIBDIR=lib \
                 -DWANT_VST_NOWINE=ON \
                 -DWANT_SOUNDIO=OFF \
                 -DWANT_GIG=OFF \
                 -DWANT_QT5=ON .
build      : |
    %ninja_build
install    : |
    %ninja_install
