name       : lmms
version    : 1.2.2
release    : 22
source     :
    - git|https://github.com/LMMS/lmms.git : v1.2.2
homepage   : https://lmms.io/
license    : GPL-2.0-or-later
component  : multimedia.audio
summary    : Free cross-platform alternative to commercial music production suites like FL Studio®
description: |
    LMMS is a free cross-platform alternative to commercial programs like FL Studio®, which allow you to produce music with your computer. This includes the creation of melodies and beats, the synthesis and mixing of sounds, and arranging of samples. You can have fun with your MIDI-keyboard and much more; all in a user-friendly and modern interface.
builddeps  :
    - pkgconfig(Qt5Help)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(alsa)
    - pkgconfig(carla-standalone)
    - pkgconfig(fftw3)
    - pkgconfig(fluidsynth)
    - pkgconfig(gig)
    - pkgconfig(jack)
    - pkgconfig(libpulse)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(samplerate)
    - pkgconfig(sdl)
    - pkgconfig(sndfile)
    - pkgconfig(sndio)
    - pkgconfig(xcb-keysyms)
    - pkgconfig(xcb-util)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(xft)
    - doxygen
    - fltk-devel
    - glibc-32bit-devel
    - ladspa-devel
    - lame-devel
    - stk-devel
rundeps    :
    - fluid-soundfont
    - libgig
setup      : |
    %patch -p1 < $pkgfiles/lmms-carla-export.patch
    %cmake_ninja -DCMAKE_INSTALL_PREFIX=/usr \
                 -DCMAKE_INSTALL_LIBDIR=%libdir% \
                 -DOpenGL_GL_PREFERENCE=GLVND \
                 -DWANT_QT5=ON \
                 -DWANT_SOUNDIO=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
    find $installdir/%libdir% -name '*.a' -delete
