name       : lmms
version    : 1.1.3
release    : 1
source     :
    - https://github.com/LMMS/lmms/archive/v1.1.3.tar.gz : 59338e7b90e02fe18db73114aefe479c0e6d1e0e366185d71ea5c1a1e0f9e6bc
license    : GPL-2.0 # CHECK ME
component  : multimedia.audio
summary    : LMMS is a free cross-platform alternative to commercial programs like FL Studio®
description: |
    LMMS is a free cross-platform alternative to commercial programs like FL Studio®, which allow you to produce music with your computer. This includes the creation of melodies and beats, the synthesis and mixing of sounds, and arranging of samples. You can have fun with your MIDI-keyboard and much more; all in a user-friendly and modern interface.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(fftw3)
    - pkgconfig(jack)
    - pkgconfig(ogg)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(libpulse)
    - pkgconfig(QtCore)
    - pkgconfig(samplerate)
    - pkgconfig(sdl)
    - pkgconfig(sndfile)
    - pkgconfig(vorbis)
setup      : |
    sed -i "s/ADD_SUBDIRECTORY(zynaddsubfx)//" plugins/CMakeLists.txt
    %cmake -DCMAKE_INSTALL_PREFIX=/usr -DQT_RCC_EXECUTABLE=rcc-qt4 \
           -DWANT_CARLA=OFF -DWANT_SF2=OFF -DWANT_STK=OFF -DWANT_VST=OFF -DWANT_VST_NOWINE=ON .
build      : |
    %make
install    : |
    %make_install
